#!/usr/bin/Rscript 

args <- commandArgs(TRUE)
pkg <- tail(args, 1L)

setwd( "~/git" )
system( sprintf( "rm -frv %s/src/*o", pkg ) )
Rcpp::compileAttributes( pkg )
system( sprintf( "R CMD INSTALL %s", pkg ) )

