#!/usr/bin/Rscript 

Sys.setenv( "USE_CXX1X" = "yes" )
args <- commandArgs(TRUE)
pkg <- tail(args, 1L)

filter <- if( length( where <- grep( "^[-]f", args ) ) ){
  gsub( "^[-]f", "", args[where][1] )  
}

setwd( "~/git/Rcpp-test" )
library(methods)
library(devtools)
load_all( "~/git/attributes" )
library(testthat)
library(pkg, character.only = TRUE)
test_dir('.', filter = filter)

